name: 🚀 Deploy Frontend to EC2

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Sync frontend code (excluding node_modules)
        run: |
          rsync -avz --exclude 'node_modules' -e "ssh -o StrictHostKeyChecking=no" ./fastprint-frontend/ ubuntu@${{ secrets.EC2_HOST }}:~/frontend/FastPrint-Frontend/fastprint-frontend/

      - name: Install dependencies & restart frontend with PM2
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            cd ~/frontend/FastPrint-Frontend/fastprint-frontend

            # Install/update Node modules
            npm install

            # Restart frontend using PM2
            pm2 stop frontend || true
            pm2 start npm --name frontend -- start
            pm2 save

            echo "Deployment successful using PM2!"
          EOF
